{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mushanyux.mushanim",
    "module": "MSIMLib_local",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "MSIMLib_local-1.0.7.aar",
          "url": "MSIMLib_local-1.0.7.aar",
          "size": 619939,
          "sha512": "13b47e667c6f7be5e8fb9d3d77466ac4379452ab1ebcaf5b89eddefab4466c6c3cae1dbbbc4c2aaf7938d52998ae97470ad7527fc8405702ade234ddabbb8b81",
          "sha256": "a628c4a7d2aa49fa6f4d9d250b6cedebab7de9de0d26d3642d736c48fc9c2f95",
          "sha1": "3f8c4711432d99c30dddf552e396a16ecba353f6",
          "md5": "6f0f88ec0585a75f5590aff96860e4e5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "net.zetetic",
          "module": "android-database-sqlcipher",
          "version": {
            "requires": "4.5.4"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "MSIMLib_local-1.0.7.aar",
          "url": "MSIMLib_local-1.0.7.aar",
          "size": 619939,
          "sha512": "13b47e667c6f7be5e8fb9d3d77466ac4379452ab1ebcaf5b89eddefab4466c6c3cae1dbbbc4c2aaf7938d52998ae97470ad7527fc8405702ade234ddabbb8b81",
          "sha256": "a628c4a7d2aa49fa6f4d9d250b6cedebab7de9de0d26d3642d736c48fc9c2f95",
          "sha1": "3f8c4711432d99c30dddf552e396a16ecba353f6",
          "md5": "6f0f88ec0585a75f5590aff96860e4e5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "MSIMLib_local-1.0.7-sources.jar",
          "url": "MSIMLib_local-1.0.7-sources.jar",
          "size": 316669,
          "sha512": "a45b703f643fca49627490eb415652ba97c8e8dc7d55dd4b8d3bf23193a1f7dc15f30d634af708a1a77ce03ce85691e05f8bf3826324e2ef2a68ea83fcaac650",
          "sha256": "0e32a791b1819a4c002a6d3ce74063af73a42dfdd93db1044fed3cc3345eafa0",
          "sha1": "e17bc848333d8cb3da54652a0015a216d542d2cd",
          "md5": "5956ab17eec04cef35fff54481d5baeb"
        }
      ]
    }
  ]
}
